dist: trusty
os: linux
 
language: node_js
node_js:
  - lts/*

branches:
  only:
    - master # 只监测 master 分支上的 commit
 
cache:
  directories:
     - ./node_modules

before_install:
  - npm i -g yarn # 全局安装 yarn
 
install:
  - yarn # 安装 package.json 中的依赖包

# before_script:
#   - git submodule init # 更新子模块
#   - git submodule update

script:
  - yarn build

after_script:
  - cd ./src/dist
  - git init
  - git config --global user.name "ruofei"
  - git config --global user.email "rf.wangchn@gmail.com"
  - git add .
  - git commit -m "Updated by Travis-CI."
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages # 发布到 gh-pages 分支

env:
  global:
    - GH_REF: 'github.com/smpower/git.ruofei.site.git'
