# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Vuepress Site to Github Pages on gh-pages Branch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install dependencies & Build static
      run: yarn && yarn build
    - name: Copy CNAME file to dist folder & cd dist folder
      run: cp ./CNAME ./src/.vuepress/dist && cd ./src/.vuepress/dist
    - name: Initialize git repository & configurate it
      run: git init && git config user.name 'ruofei' && git config user.email 'rf.wangchn@gmail.com'
    - name: Commited
      run: git add . && git commit -m 'Deploy Vuepress site'
    - name: Publish
      run: git push --force --quiet "https://${ACCESS_TOKEN}@github.com/smpower/git.ruofei.site.git" master:gh-pages # 发布到 gh-pages 分支
    - name: End
      run: echo "Vuepress site has deployed to GitHub Pages."