# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Vuepress Site to Github Pages on gh-pages Branch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: rreichel3/vuepress-github-actions-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_REPOSITORY: smpower/git-cn.ruofei.site
        BUILD_DIR: src/.vuepress/dist # The folder, the action should deploy.
        BUILD_SCRIPT: yarn && yarn build # The build script the action should run prior to deploying.
        PAGES_CNAME: git-cn.ruofei.site
